version: '2.11'
rpc:
    listen: 'tcp://127.0.0.1:11001'
http:
    address: '0.0.0.0:9000'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100
            exec_ttl: 60s
server:
    command: 'D:/xampp/php/php.exe -d display_errors=1 -d display_startup_errors=1 -d error_reporting=E_ALL worker.php'
    relay: pipes
    relay_timeout: 60s
metrics:
    address: '127.0.0.1:2112'
